site_name: Breezy — Documentation
site_description: Documentation technique du réseau social Breezy
theme:
  name: material
  language: fr
  palette:
    primary: indigo
nav:
  - Accueil: index.md
  - Architecture:
    - Vue d'ensemble: architecture/vue-ensemble.md
    - Communication inter-services: architecture/communication-services.md
    - Flux de données: architecture/flux-donnees.md
    - Docker & Déploiement: architecture/docker-deploiement.md
  - Services:
    - API Gateway: services/gateway.md
    - Auth Service: services/auth-service.md
    - User Service: services/user-service.md
    - Post Service: services/post-service.md
    - Profil Service: services/profil-service.md
    - Frontend: services/frontend.md
  - Données:
    - Schéma PostgreSQL: donnees/schema-postgresql.md
    - Schéma MongoDB: donnees/schema-mongodb.md
  - Sécurité:
    - Authentification: securite/authentification.md
  - Fonctionnalités:
    - Couverture: fonctionnalites/couverture-fx.md
  - API:
    - Routes complètes: api/routes-completes.md
  - Soutenance:
    - Questions générales: soutenance/questions-generales.md
    - Questions par membre: soutenance/questions-par-membre.md
    - Limites et évolutions: soutenance/limites-evolutions.md
  - Journal des modifications: CHANGELOG_DOC.md
